name: Build and Push Release

on:
  push:
    tags:
       - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ubiboot

      - name: Install podman
        run: |
          set -exu \
          && sudo apt-get -yq update \
          && sudo apt-get -yq install podman \
          && podman system migrate

      - name: Build UBIBoot
        run: |
          set -exu \
          && cd ubiboot \
          && ./build-env/build-env-exec.sh make CONFIG=a320 \
          && ./build-env/build-env-exec.sh make CONFIG=gcw0 \
          && ./build-env/build-env-exec.sh make CONFIG=lepus \
          && ./build-env/build-env-exec.sh make CONFIG=rs90

      - name: Push Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./ubiboot/output/a320/ubiboot-a320.bin
            ./ubiboot/output/a320/ubiboot-a320.elf
            ./ubiboot/output/gcw0/ubiboot-rg350.bin
            ./ubiboot/output/gcw0/ubiboot-rg350.elf
            ./ubiboot/output/gcw0/ubiboot-v11_ddr2_256mb.bin
            ./ubiboot/output/gcw0/ubiboot-v11_ddr2_256mb.elf
            ./ubiboot/output/gcw0/ubiboot-v11_ddr2_512mb.bin
            ./ubiboot/output/gcw0/ubiboot-v11_ddr2_512mb.elf
            ./ubiboot/output/gcw0/ubiboot-v20_mddr_512mb.bin
            ./ubiboot/output/gcw0/ubiboot-v20_mddr_512mb.elf
            ./ubiboot/output/lepus/ubiboot-gopher2b.bin
            ./ubiboot/output/lepus/ubiboot-gopher2b.elf
            ./ubiboot/output/lepus/ubiboot-gopher2.bin
            ./ubiboot/output/lepus/ubiboot-gopher2.elf
            ./ubiboot/output/lepus/ubiboot-lepus.bin
            ./ubiboot/output/lepus/ubiboot-lepus.elf
            ./ubiboot/output/rs90/ubiboot-v21.bin
            ./ubiboot/output/rs90/ubiboot-v21.elf
            ./ubiboot/output/rs90/ubiboot-v30.bin
            ./ubiboot/output/rs90/ubiboot-v30.elf
